### ISSUE TITLE
[refactor] Automate Item-/-Mesher registration.

### ISSUE THREAD

**Issue by Longor1996** [tiffit/TaleCraft#11]
I haven't looked into this yet (not much time on hand), but if there is a way to automate the registration of items in the mesher (see here: https://github.com/tiffit/TaleCraft/blob/master/src/main/java/de/longor/talecraft/client/ClientRenderer.java#L167) someone should do it at some point. As it is now there are several steps too many to registering an item and that is just silly.

The same thing goes for the registration of block models (same file).

**Comment by tiffit** [comment]
Done.
