### ISSUE TITLE
[feature] Fade Effect

### ISSUE THREAD

**Issue by Longor1996** [tiffit/TaleCraft#12]
Steps to implement this:

1. Find a code hook that is placed right behind the rendering of the ingame GUI (hand & HUD).
2. Take the original fade-code from here: https://github.com/tiffit/TaleCraft/blob/master/src/main/java/de/longor/talecraft/client/ClientRenderer.java#L493 and ...
3. ...implement it at the hook from step 1.
4. Add a /tc_fade-command and a network packet to handle fade effects.
5. Make sure that the fade effect does NOT affect the normal GUI rendering.
6. Make sure that the fade effect does not last for more than ~5 seconds.
7. (Optional) Make it possible to use a textured instead of a plain colored fade.

**Comment by tiffit** [comment]
Done.
