### ISSUE TITLE
Let the layout of list's in GUI's be handled by QADListLayout

### ISSUE THREAD

**Issue by Longor1996** [tiffit/TaleCraft#14]
As the title says; find all places where the layout of a list is manually created and replace the manual list layout with the automatic QADListLayout (if possible).

Sidenote: To make more complex layouts simpler, make it possible to add layout parameters to components; possibly as a `Map<String,Object>` or a `Map<String,NBTTag>` right inside the QADComponent class.

**Comment by tiffit** [comment]
I can't seem to figure out how to use the QADListLayout

**Comment by Longor1996** [comment]
Call `setLayout(new QADListLayout())` right after creating a new `QADPanel`; the rest is automagic.

**Comment by tiffit** [comment]
Done.
