### ISSUE TITLE
[refactor] Move rendering of Item 3D metadata into separate classes.

### ISSUE THREAD

**Issue by Longor1996** [tiffit/TaleCraft#15]
This should be simple: Create a mapping of item type (using Item instances) to metadata renderers (new class needed) and let ItemMetaWorldRenderer use that mapping to find and invoke the correct renderer.

(Note that metadata is only shown in creative)
Possible uses for 3D item metadata:

- Render wirebox around selected entity with Wand/NPCEditor.
- Render 3D cursor and bounds for Voxelator tool.
- ...

Note: Make sure that the code allows adding a 3D metadata renderer to ANY item (vanilla or TC, it shouldn't matter).

**Comment by tiffit** [comment]
What exactly do you mean by this? What is a metadata renderer?

**Comment by Longor1996** [comment]
Its the thing that takes a Item and renders information about it into the (3D) world.

**Comment by tiffit** [comment]
Alright, done
