### ISSUE TITLE
Spike blocks should not be TileEntity's.

### ISSUE THREAD

**Issue by Longor1996** [tiffit/TaleCraft#16]
And the reason why is that people might want to place a _lot_ of spikes and they will be pissed when the game starts slowing down, because right now Spike blocks are TileEntities. That is not okay.

Generally: Do not make blocks TileEntities if there is a chance that there will be a lot of them placed in the world.

1. Make block models for the different states of a Spike (e.g: ON_UP, ON_DOWN, OFF_UP, ...).
2. Turn the Spike blocks (TCBlockContainer) back into normal blocks (TCBlock) and add two blockstates `ACTIVE` and `DIRECTION`.
3. Make the trigger method simply toggle the `ACTIVE` blockstate and run a block update _without updating the neighbouring blocks_.
4. Make the rendering of Spike blocks use the previously made block models.
5. Either give the Spike block a simple GUI to change the blockstates or use a existing tool.
6. Done.

**Comment by tiffit** [comment]
Done
