### ISSUE TITLE
Prevent use of 'real' names in reflection and caching of results.

### ISSUE THREAD

**Issue by Longor1996** [tiffit/TaleCraft#17]
Friendly reminder: Finding and updating the names of fields/methods/classes for `java.util.reflection` is no fun at all; so I suggest making use of the facts that _a)_ fields have types and _b)_ they can be iterated over (Class.get[Declared]Fields) to locate inaccessible fields in the original Minecraft code, instead of writing down the names of these fields right inside the TC source.

Furthermore: If reflection is used to get a list of fields/names/methods, make sure to cache the result somewhere. Reflection can and will come at a significant performance loss.

Problematic classes are thus:

- TaleCraft/src/main/java/tiffit/talecraft/util/ReflectionUtil.java
- TaleCraft/src/main/java/de/longor/talecraft/commands/AttackCommand.java
- TaleCraft/src/main/java/de/longor/talecraft/script/GlobalScriptManager.java
- TaleCraft/src/main/java/de/longor/talecraft/TCSoundHandler.java

**Comment by tiffit** [comment]
Fixed.
