### ISSUE TITLE
Update to Forge for Minecraft 1.10

### ISSUE THREAD

**Issue by Longor1996** [tiffit/TaleCraft#18]
Update TaleCraft to the newest Forge version, making it compatible with Minecraft 1.10.
No large/deep changes should be necessary, since the Forge-Team made sure to keep everything compatible.

**Comment by ErrorCraftLP** [comment]
Some smaller changes must be made probably because TC is on 1.9 currently, not on 1.9.4.

**Comment by tiffit** [comment]
Already done that :) . Version v0.2.7 was built in 1.10.
