### ISSUE TITLE
Crash rendering various blocks

### ISSUE THREAD

**Issue by Arkia** [tiffit/TaleCraft#19]
When placing a spike block or loading a world that contains a spike block Minecraft crashes. Minecraft also crashes when trying to render a SummonBlock if it was placed in an earlier version of the mod.

Spike Block: [http://pastebin.com/7AH6TRBA](http://pastebin.com/7AH6TRBA)
Summon Block: [http://pastebin.com/ybpkjxk6](http://pastebin.com/ybpkjxk6)

**Comment by tiffit** [comment]
Fixed in v0.2.8!
