### ISSUE TITLE
Adding Custom NPC Skins

### ISSUE THREAD

**Issue by pwnage-pineapple** [tiffit/TaleCraft#24]
How might one add custom skins for NPCs? The only tutorial I found on the wiki is out-of-date as of TaleCraft 0.0.2. Is this still the only method, is there a better way, or should I bundle a resource pack with the map in order to achieve this?

**Comment by tiffit** [comment]
The only way to do this is to bundle a resource pack with the map.

**Comment by Longor1996** [comment]
Is this issue resolved? If so, i'd like to close it.
