### ISSUE TITLE
[feature] New Item: Decorator Tool / Structure Stamp

### ISSUE THREAD

**Issue by Longor1996** [tiffit/TaleCraft#25]
A tool that lets you 'stamp' decorations like trees, grass, icespikes... right into the world, possibly with a preview of the 3D structure.

[Quick Sketch](http://i.imgur.com/o53gizI.jpg)

* There should be predefined structures and generators to plant.
* It should be possible to select any schematic and plant it.
* It should be possible to write a script that generates things.
* It should be possible to let the decorator 'spread plant' structures randomly.
* A decorator should only add or change blocks, never 'remove' them.

Base interface sketch:
```java
  interface Decorator {
    /**
      @param world The world to plant the structure in.
      @param positions Positions to plant structures at.
      @param options Options for the decorator (eg: Tree height/type, plant radius...).
      @return Number of blocks added/changed.
    **/
    int plant(World world, BlockPos[] positions, NBTTagCompound options);
  }
  
  class SchematicDecorator implements Decorator {}
  class JavascriptDecorator implements Decorator {}

  abstract class StaticDecorator implements Decorator {}
  class TreeDecorator extends StaticDecorator {}
  class GrassDecorator extends StaticDecorator {}
```

**Comment by tiffit** [comment]
Done!
