### ISSUE TITLE
Allow copying of entities with the Copy tool.

### ISSUE THREAD

**Issue by Longor1996** [tiffit/TaleCraft#38]
As the name of the Issue suggests, it should be made possible to copy entities with the Copy Tool.
Most of the functionaility already exists in the clipboard-system, we just need to add an interface.

The simplest option would be to copy by leftclicking an entity with the Copy Tool.

**Comment by tiffit** [comment]
I have already renamed the NPC cloner to the Entity cloner. It has the same functionalities as the NPC cloner, except not limited to one type of entity. There is no need for this since that already exists.
