### ISSUE TITLE
'MovingBlock' as better alternative to 'FallingSand' Entity

### ISSUE THREAD

**Issue by Longor1996** [tiffit/TaleCraft#40]
A entity that can take the form of any block.

Proposed Features:
- [x] Is persistent.
- [x] Can represent *any* block(state) in the game.
- [x] Does _not_ plant itself as block unless told to do so by a script.
- [x] Can only be removed trough a script or /kill.
- [x] Can be scripted with events: `onTick`, `onIntersect`, `onInteract` and `onDeath`.
- [x] Can be mounted by other entities, with custom passenger offsets.
- [x] Can be made invisible.
- [x] Can be made pushable.
- [x] Can have gravity toggled on/off.
- [x] Can have collision enabled (using the actual block hitbox).
- [ ] Can be rotated and scaled graphically.
  - Requires copy of the FallingBlock renderer.
  - [ ] Scaling affects bounding box.
  - [ ] Rotation affects bounding box. (possibly useless idea?)

**Comment by tiffit** [comment]
EntityFallingBlock (which EntityMovingBlock extends) extends Entity and not EntityLiving. Only EntityLivings can despawn when not persistent, so persistence here is not a worry.

**Comment by tiffit** [comment]
The last feature will be a bit harder to implement, so I will do it in the next update.

**Comment by Longor1996** [comment]
Rotation and scaling aren't going to be added, unless someone actually requests them. Closing.
