### ISSUE TITLE
[change] Voxelator Tool: Completely redo the GUI.

### ISSUE THREAD

**Issue by Longor1996** [tiffit/TaleCraft#43]
The Voxelator GUI should be reworked, not only because its missing some (very important) things, but also because the creation of the GUI can now be automated with the BrushParameter system that was added a few days ago.

Right now it should be enough if the GUI is generated so its structure is:

  - A simple toolbar:
    - button:cancel; Closes the GUI and resets the item NBT to the previous values.
    - button:apply; Applies the changes to the Voxelator (send item NBT to server).
  - 3 columns of equal width:
    - (scroll-)panel:shape; (+ dropdownbox for shape selection)
    - (scroll-)panel:filter; (+ dropdownbox for filter selection)
    - (scroll-)panel:action; (+ dropdownbox for action selection)

Implementing this GUI requires a dropdownbox component for the QAD GUI.

**Comment by tiffit** [comment]
Done!
