### ISSUE TITLE
Sending an INVERT state to a memory block doesn’t reset it

### ISSUE THREAD

**Issue by Ryan8781** [tiffit/TaleCraft#48]
Instead, it behaves just like the ON state.

**Comment by Longor1996** [comment]
Fixed as of latest commits.

**Comment by Ryan8781** [comment]
I just thought, wouldn't it make more sense if an INVERT state inverted the memory block's "triggered" state (set it to true if it's false and set it to false if it's true), while an OFF state would reset it (set it to false)?

**Comment by Longor1996** [comment]
That actually does make sense...
