### ISSUE TITLE
No way to disable default music

### ISSUE THREAD

**Issue by Ryan8781** [tiffit/TaleCraft#49]
There should be a way to disable the default Minecraft music, perhaps via a gamerule.

**Comment by Longor1996** [comment]
This requires that gamerules are syncchronized with the client, since right now they are entirely server-side.

**Comment by Longor1996** [comment]
Note that the above commit is only a 'fix' in the sense that it would work if the flag is set. Problem is that its impossible to change the NBT data of a player, since `/entitydata` simply doesn't allow that.

**Comment by Longor1996** [comment]
If Issue #54 is implemented, the above 'fix' can actually be used.

**Comment by tiffit** [comment]
Issue #54 was implemented and that will be the fix for now. I will sync gamerules and add a gamerule in the next update.
