### ISSUE TITLE
The “Trigger this invoke” button does not work

### ISSUE THREAD

**Issue by Ryan8781** [tiffit/TaleCraft#50]
It never worked for me in the first place.

**Comment by Longor1996** [comment]
To fix this, and also allow entities to posses and call invokes, a 'data path' system is needed which can locate specific NBT tag compounds within tileentities/entities/itemstacks by the means of a path that can be sent between client and server as NBT.

**Comment by tiffit** [comment]
Added a temporary fix for this, Longor's system will be implemented in the near future.
