### ISSUE TITLE
Add command to change player entity data.

### ISSUE THREAD

**Issue by Longor1996** [tiffit/TaleCraft#54]
This is both simple, and hard.

The command should, basically, select players using a entity selector, then merge the textual NBT data given to the command with the data of every selected player. This is simple.

The hard part is that specific tags must be forcefully excluded from the merge-data, since it would cause serious problems and bugs otherwise.

To implement this we have to identify which tags of a player entity are 'unsafe' to change.

The command syntax should be:
`/tc_playerdata <selector> {merge-data}`

**Comment by tiffit** [comment]
Done
