### ISSUE TITLE
Cannot type numbers into the block selection field

### ISSUE THREAD

**Issue by Ryan8781** [tiffit/TaleCraft#69]
When using the block selection GUI element, it's possible to search for blocks by typing the block name there and then clicking the appropriate block from the search results to select it. However, I can't seem to be able to type numbers into the search field, which means I cannot select blocks like “Deco Stone A14”.

**Comment by Longor1996** [comment]
Fixed and done. @tiffit will have to create a new release, or you compile your own version.
