### ISSUE TITLE
Refactor damage sources in AttackCommand

### ISSUE THREAD

**Issue by Longor1996** [tiffit/TaleCraft#9]
I looked at the other (closed) issues and stumbled upon the AttackCommand class, and to my horror I found that I hardcoded all of the damagesources in the class.

Suggestion:
Move the damagesources into a list or array and use that in the class.

[The file in question.](https://github.com/tiffit/TaleCraft/blob/master/src/main/java/de/longor/talecraft/commands/AttackCommand.java)

**Comment by tiffit** [comment]
I probably will use reflection so that if minecraft were to add more damagesources, then I don't have to change anything.

**Comment by tiffit** [comment]
Yeah, that works. No more hardcoded damagesources.
